sudo: required
dist: xenial

language:
    - c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - doxygen
    - valgrind
    - clang
    - gcc
    - gcc-7
    - python3-pip
    - python3-setuptools
    - ninja-build
script: test/travis-build.sh
install: test/travis-install.sh

